baseURL = "https://theLucius7.github.io/"
languageCode = "zh-cn"
title = "Hi, I'm Lucius7🥺"

[markup]
  [markup.goldmark.renderer]
    unsafe = true

[module]
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"