#!/usr/bin/env node

import { createHash } from "node:crypto";
import { mkdir, readdir, readFile, rm, stat, writeFile } from "node:fs/promises";
import path from "node:path";

const repoRoot = process.cwd();
const outputDir = path.join(repoRoot, "static", "fonts", "google");
const outputCss = path.join(outputDir, "site-fonts.css");
const chromeUA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36";

const sourcePaths = [
  path.join(repoRoot, "content"),
  path.join(repoRoot, "layouts"),
  path.join(repoRoot, "hugo.toml"),
];

const ascii =
  " !\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~";

async function walk(targetPath) {
  const info = await stat(targetPath);
  if (info.isFile()) {
    return [targetPath];
  }

  const entries = await readdir(targetPath, { withFileTypes: true });
  const files = await Promise.all(
    entries.map(async (entry) => {
      const entryPath = path.join(targetPath, entry.name);
      if (entry.isDirectory()) {
        return walk(entryPath);
      }
      return [entryPath];
    }),
  );

  return files.flat();
}

async function collectCharset() {
  const charset = new Set(ascii.split(""));

  for (const sourcePath of sourcePaths) {
    const files = await walk(sourcePath);
    for (const file of files) {
      const text = await readFile(file, "utf8");
      for (const char of text) {
        if (!/\s/u.test(char) || char === " ") {
          charset.add(char);
        }
      }
    }
  }

  return [...charset].sort((left, right) => left.codePointAt(0) - right.codePointAt(0)).join("");
}

async function download(url) {
  const response = await fetch(url, {
    headers: {
      "User-Agent": chromeUA,
    },
  });

  if (!response.ok) {
    throw new Error(`Failed to fetch ${url}: ${response.status} ${response.statusText}`);
  }

  return response;
}

function filenameForUrl(url) {
  const parsed = new URL(url);
  const pathname = path.basename(parsed.pathname) || "font";
  const actualExtension = path.extname(pathname);
  const extension = actualExtension || ".woff2";
  const stem = actualExtension ? pathname.slice(0, pathname.length - actualExtension.length) : pathname;
  const hash = createHash("sha1").update(url).digest("hex").slice(0, 12);
  return `${stem}-${hash}${extension}`;
}

async function main() {
  await mkdir(outputDir, { recursive: true });

  const existing = await readdir(outputDir).catch(() => []);
  await Promise.all(existing.map((file) => rm(path.join(outputDir, file), { force: true })));

  const text = await collectCharset();
  const fontCssUrl =
    "https://fonts.googleapis.com/css2?family=Inter:wght@400;500;700&family=Noto+Sans+SC:wght@400;500;700&display=swap&text=" +
    encodeURIComponent(text);

  const cssResponse = await download(fontCssUrl);
  const remoteCss = await cssResponse.text();

  const urls = [...new Set(remoteCss.match(/https:\/\/fonts\.gstatic\.com\/[^)"'\s]+/g) ?? [])];
  if (urls.length === 0) {
    throw new Error("Google Fonts CSS did not contain any downloadable font URLs.");
  }

  const urlToLocal = new Map();
  await Promise.all(
    urls.map(async (url) => {
      const filename = filenameForUrl(url);
      const fontResponse = await download(url);
      const fontBytes = Buffer.from(await fontResponse.arrayBuffer());
      await writeFile(path.join(outputDir, filename), fontBytes);
      urlToLocal.set(url, `/fonts/google/${filename}`);
    }),
  );

  let localCss = remoteCss;
  for (const [remoteUrl, localUrl] of urlToLocal) {
    localCss = localCss.split(remoteUrl).join(localUrl);
  }

  const header =
    "/* Generated by scripts/sync_google_fonts.mjs from Google Fonts.\n" +
    "   Families: Inter, Noto Sans SC\n" +
    "   Weights: 400, 500, 700\n" +
    "   The subset is derived from the current site content, layouts, and config. */\n\n";

  await writeFile(outputCss, header + localCss);

  console.log(
    JSON.stringify(
      {
        css: path.relative(repoRoot, outputCss),
        downloadedFiles: urls.length,
        subsetCharacters: [...text].length,
      },
      null,
      2,
    ),
  );
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
